# Generated by Django 5.0.6 on 2024-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0007_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
