# Generated by Django 5.0.6 on 2024-06-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0011_post_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='title', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
