# Generated by Django 5.0.6 on 2024-06-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0012_post_avatar_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
